services:
  postgres:
    image: postgres:latest
    container_name: email-manager-container
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emailmanager_db

volumes:
  db-data:
